Create database tables for applications Projects
Synt4xL4b/sup-backend pull request #5
Opened 2024-08-21 16:41 UTC by BulatKayrov

Создал таблицы согласно ТЗ. просьба прокомментировать

2024-08-21 18:26 UTC, hutji requested changes
Оставил некоторые комментарии по поводу полей в моделях. Также предлагаю choices вынести в choice_classes.py и добавить проверки(валидацию данных). Вынести в общий модуль validators откуда могут импортировать разные модели в разных приложениях. Тут вопрос в архитектуре, куда запихать папку validators? в apps?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    DISCUSSION = "В обсуждении"
Предлагаю вынести в choice_classes.py

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    slug = models.SlugField(unique=True, verbose_name="Ссылка")
нужно ли поле slug?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=50, verbose_name="Название")
В тз написано, что допускаются буквы латиницы и кириллицы, поэтому стоит добавить валидацию для этого поля. В пулл реквесте Алмаза об этом писал. Предлагаю вынести в общую папку "validators" валидацию иначе в разных приложениях будет дубликация кода.

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=50, verbose_name="Название")
Может ли быть несколько фич с одинаковым названием? Если нет то стоит добавить unique=True.

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    importance = models.PositiveIntegerField(
устанавливается ли здесь MaxValueValidator?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=50, verbose_name="Название")
Тоже должен присутствовать RegexValidator. 
unique=True?

`        validators=[
            RegexValidator(
                regex=r"^[a-zA-Zа-яА-Я\s]*$",
                message="Допускаются только буквы латиницы и кириллицы.",
                code="invalid_name",
            ),
        ],`

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    importance = models.PositiveIntegerField(
Валидация на макс значение?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    description = models.TextField(max_length=10000, verbose_name="Описание")
blank=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    tags = models.ManyToManyField(
blank=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    importance = models.PositiveIntegerField(
blank=True? Если не определена важность задачи

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    participants = models.ManyToManyField(
blank=True? Если не выбраны еще исполнители

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    tags = models.ManyToManyField(
blank=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    description = models.TextField(max_length=10000, verbose_name="Описание")
в тз и по дизайну это поле необязательное

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    NEW = "Новая"
Тоже предлагаю вынести в choice_classes

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    slug = models.SlugField(unique=True, verbose_name="Ссылка")
по дизайну есть выбор цвета тега

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=20, verbose_name="Название")
validators=[
            RegexValidator(
                regex=r"^[a-zA-Zа-яА-Я\s]*$",
                message="Допускаются только буквы латиницы и кириллицы.",
                code="invalid_name",
            ),
        ],

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=20, verbose_name="Название")
unique=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    participants = models.ManyToManyField(
blank=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    responsible = models.ForeignKey(
blank=True?

2024-08-21 18:26 UTC, hutji commented on src/apps/projects/models.py
> +    STATUS_CHOICES = [
choice_classes.py

2024-08-21 19:01 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    slug = models.SlugField(unique=True, verbose_name="Ссылка")
Можно по полю pk вытаскивать проект и редактировать его. Но мне кажется правильнее использовать slug. 
поле slug предлагаю использовать у всех моделей. так как их должны редактировать

2024-08-21 20:16 UTC, hutji commented on src/apps/projects/models.py
> +    slug = models.SlugField(unique=True, verbose_name="Ссылка")
Ок

2024-08-21 21:00 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    DISCUSSION = "В обсуждении"
Вынес

2024-08-21 21:00 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    name = models.CharField(max_length=50, verbose_name="Название")
С корректировал

2024-08-21 21:01 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    importance = models.PositiveIntegerField(
установил

2024-08-21 21:02 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    participants = models.ManyToManyField(
В связях m2m поправил

2024-08-21 21:02 UTC, BulatKayrov commented on src/apps/projects/models.py
> +    responsible = models.ForeignKey(
В связях m2m поправил

2024-08-21 21:05 UTC, BulatKayrov commented
Накидал вьюх. Урлы добавил. В модели дополнил методы. к модели Task добавил связь связь с User (автор, так как мне кажется задачу только админ может создавать) остались шаблоны. сейчас там заглушки.

2024-08-22 04:14 UTC, hutji commented on src/apps/projects/admin.py
> +from .models import Color, Feature, Project, Tags, Task
Предлагаю указывать полные пути к импорту, например from apps.projects.models

2024-08-22 04:14 UTC, hutji commented on src/apps/projects/views.py
> +from .forms import FeatureForm, ProjectForm, TagForm, TaskForm
Везде предлагаю указывать полные пути к импорту

2024-08-22 04:14 UTC, hutji commented on src/apps/projects/validators.py
> +from django.core.validators import MaxValueValidator, RegexValidator
Предлагаю вынести этот файл в общую папку

2024-08-24 06:24 UTC, hutji commented on src/apps/projects/forms.py
> +from .models import Feature, Project, Tags, Task
и здесь

2024-08-24 06:24 UTC, hutji commented on src/apps/projects/models.py
> +from .choice_classes import FeatureChoices, ProjectChoices, TaskChoices
from apps.projects.choice_classes

2024-08-24 06:24 UTC, hutji commented on src/apps/projects/views.py
> +    template_name = "projects/features.html"
правильно я понимаю, что будет другой путь

2024-08-24 06:24 UTC, hutji commented on src/apps/projects/views.py
> +    queryset = Feature.objects.select_related(
можеть здесь для m2m использовать prefetch_related,  а также в queryset дублируется "tags"

2024-08-24 06:24 UTC, hutji commented on src/apps/projects/urls.py
> +app_name = "projects"
app_name = apps.projects, иначе ругаться будет

2024-08-26 02:39 UTC, SoulStalker approved these changes
ok

2024-08-26 10:06 UTC, hutji reviewed
Все ок, только можно  убрать теперь User=get_user_model() и указать CustomUser

2024-08-26 11:53 UTC, merged